#!/bin/sh

before_boil=8
after_boil=10
beep=true
tray=true

cry(){
    notify-send -t 10000 "$2" "$3"
    i=$1
    while [ $i -gt 0 ]; do
        if $beep; then beep; fi
        if $tray; then eject -r; eject -t; fi
        i=$(($i-1))
    done
}

cry 0 "Варка пошла" "Кастрюля с водой на плите. Лавровый лист и перец горошком по вкусу"
sleep ${before_boil}m
cry 1 "Вода закипела" "Посоли воду, брось пельмени, убавь газ. Можно пока замешать соус из-того-что-есть-в-холодильнике"
sleep ${after_boil}m
cry 2 "Пельмени готовы" "Идите жрать, пожалуйста!"
